all:
  hosts:
    146.190.49.200:
  children:
    webservers:
      hosts:
        remote:
          ansible_host: 146.190.49.200
          ansible_port: 22
          ansible_user: root
        # 127.0.0.1: