# Generated by Django 4.2.3 on 2023-07-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Server name or identifier', max_length=45)),
                ('ip_address', models.GenericIPAddressField()),
                ('ssh_port', models.IntegerField(default=22)),
                ('ssh_user', models.CharField(default='root', help_text='Default user', max_length=32)),
            ],
        ),
    ]
