# Generated by Django 4.2.3 on 2023-07-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_host_created_at_host_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ('-created_at',)},
        ),
    ]
