# Generated by Django 4.2.3 on 2023-07-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_access_root_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='access',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sshkeys',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sshkeys',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
