# Generated by Django 4.2.3 on 2023-07-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_access_created_at_access_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='access',
            name='last_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
